const EnumTypes={
    LENGTH:{
        INCHES:"1",
        FEET:"12",
        YARD:"36",
        CENTIMETER:"0.4"
    },
    VOLUME:{
        GALLON:"3780",
        LITRES:"1000",
        MILLILITRES:"1"
    },
    WEIGHT:{
        KILOGRAM:"1000",
        GRAM:"1",
        TONNE:"1000000"
    }
}
module.exports=EnumTypes;